name: diacritic
channels:
  - defaults
dependencies:
  - ca-certificates=2017.08.26
  - certifi=2018.1.18
  - libedit=3.1
  - libffi=3.2.1
  - ncurses=6.0
  - openssl=1.0.2n
  - pip=9.0.1
  - python=3.6.4
  - readline=7.0
  - setuptools=38.5.1
  - sqlite=3.22.0
  - tk=8.6.7
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
  - pip:
    - absl-py==0.1.11
    - appnope==0.1.0
    - astor==0.6.2
    - awscli==1.11.178
    - bleach==1.5.0
    - boto==2.48.0
    - boto3==1.6.7
    - botocore==1.9.7
    - bz2file==0.98
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.2.1
    - docutils==0.14
    - entrypoints==0.2.3
    - gast==0.2.0
    - gensim==3.4.0
    - grpcio==1.10.0
    - html5lib==0.9999999
    - idna==2.6
    - ipykernel==4.8.2
    - ipython==6.2.1
    - ipython-genutils==0.2.0
    - jedi==0.11.1
    - jinja2==2.10
    - jmespath==0.9.3
    - jsonschema==2.6.0
    - jupyter-client==5.2.2
    - jupyter-core==4.4.0
    - jupyterlab==0.31.12
    - jupyterlab-launcher==0.10.5
    - keras==2.1.5
    - kiwisolver==1.0.1
    - markdown==2.6.11
    - markupsafe==1.0
    - matplotlib==2.2.0
    - mistune==0.8.3
    - nbconvert==5.3.1
    - nbformat==4.4.0
    - nltk==3.2.5
    - notebook==5.4.0
    - numpy==1.14.2
    - pandocfilters==1.4.2
    - parso==0.1.1
    - pexpect==4.4.0
    - pickleshare==0.7.4
    - progressbar2==3.36.0
    - prompt-toolkit==1.0.15
    - protobuf==3.5.2
    - ptyprocess==0.5.2
    - pyasn1==0.3.7
    - pygments==2.2.0
    - pyparsing==2.2.0
    - python-dateutil==2.6.1
    - python-utils==2.3.0
    - pytz==2018.3
    - pyyaml==3.12
    - pyzmq==17.0.0
    - requests==2.18.4
    - rsa==3.4.2
    - s3transfer==0.1.11
    - scipy==1.0.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - six==1.11.0
    - smart-open==1.5.6
    - tensorboard==1.6.0
    - tensorflow==1.6.0
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.3.1
    - tornado==5.0
    - traitlets==4.3.2
    - urllib3==1.22
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.14.1

